---
- name: Create ansible user and push SSH key
  hosts: proxmox
  become: true
  vars:
    ansible_user_pubkey: "{{ lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"
  tasks:
    - name: Ensure ansible user exists
      user:
        name: ansible
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh directory
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Add public key to authorized_keys
      copy:
        content: "{{ ansible_user_pubkey }}"
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'

    - name: Allow ansible user to use sudo without password
      copy:
        content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/ansible
        mode: '0440'